### ISSUE TITLE
Erro ao instalar Cogroo4py em Win10

### ISSUE THREAD

**Issue by felipefcunica** [gpassero/cogroo4py#12]
Basicamente estou encontrando um erro ao tentar executar o comando:

`$python -m pip install cogroo4py
`

Comportamento esperado:
`
Dependências serem instaladas com sucesso`

Comportamento observado:

"
Collecting cogroo4py
  Using cached cogroo4py-0.4.6-py3-none-any.whl (32.7 MB)
Collecting Deprecated==1.2.13
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting JPype1==1.3.0
  Using cached JPype1-1.3.0.tar.gz (820 kB)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp310-cp310-win_amd64.whl (35 kB)
Using legacy 'setup.py install' for JPype1, since package 'wheel' is not installed.
Installing collected packages: wrapt, JPype1, Deprecated, cogroo4py
    Running setup.py install for JPype1 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\felip\Projects\CRIA\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\felip\\AppData\\Local\\Temp\\pip-install-byu_puv5\\jpype1_3d9482091cbc42b5b84f9271a76b889b\\setup.py'"'"'; __file__='"'"'C:\\Users\\felip\\AppData\\Local\\Temp\\pip-install-byu_puv5\\jpype1_3d9482091cbc42b5b84f9271a76b889b\\setup.py'"'"';f = getattr(tokenize, 
'"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\felip\AppData\Local\Temp\pip-record-y84ts2w5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\felip\Projects\CRIA\venv\include\site\python3.10\JPype1'
         cwd: C:\Users\felip\AppData\Local\Temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\
    Complete output (81 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\jpype
    copying jpype\beans.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\config.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\dbapi2.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\imports.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\nio.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\pickle.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\protocol.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\types.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_classpath.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_core.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_gui.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jarray.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jclass.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jcollection.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jcustomizer.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jexception.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jinit.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jio.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jmethod.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jobject.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jpackage.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jproxy.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jstring.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jthread.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jvmfinder.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\_pykeywords.py -> build\lib.win-amd64-3.10\jpype
    copying jpype\__init__.py -> build\lib.win-amd64-3.10\jpype
    package init file 'jpype\_pyinstaller\__init__.py' not found (or not a regular file)
    creating build\lib.win-amd64-3.10\jpype\_pyinstaller
    copying jpype\_pyinstaller\entry_points.py -> build\lib.win-amd64-3.10\jpype\_pyinstaller
    copying jpype\_pyinstaller\example.py -> build\lib.win-amd64-3.10\jpype\_pyinstaller
    copying jpype\_pyinstaller\hook-jpype.py -> build\lib.win-amd64-3.10\jpype\_pyinstaller
    copying jpype\_pyinstaller\test_jpype_pyinstaller.py -> build\lib.win-amd64-3.10\jpype\_pyinstaller
    copying jpype\_core.pyi -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jcollection.pyi -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jio.pyi -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jstring.pyi -> build\lib.win-amd64-3.10\jpype
    copying jpype\_jthread.pyi -> build\lib.win-amd64-3.10\jpype
    running build_ext
    Call build extensions
    Using Jar cache
    copying native\jars\org.jpype.jar -> build\lib.win-amd64-3.10
    Call build ext
    building '_jpype' extension
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\native
    creating build\temp.win-amd64-3.10\Release\native\common
    creating build\temp.win-amd64-3.10\Release\native\python
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Inative\common\include -Inative\python\include -Inative\embedded\include -Inative\jni_include -IC:\Users\felip\Projects\CRIA\venv\include -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpnative\common\jp_array.cpp /Fobuild\temp.win-amd64-3.10\Release\native\common\jp_array.obj /Zi /EHsc /std:c++14
    jp_array.cpp
    C:\Users\felip\AppData\Local\Temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\python\include\jp_pythontypes.h(284): error C2061: erro de sintaxe: identificador 'ssize_t'       
    C:\Users\felip\AppData\Local\Temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\python\include\jp_pythontypes.h(285): error C2805: 'operator [' bin rio possui poucos parƒmetros  
    C:\Users\felip\AppData\Local\Temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\python\include\jp_pythontypes.h(285): error C2333: 'JPPyObjectVector::operator []': erro na declara‡Æo da fun‡Æo; ignorando corpo da fun‡Æo
    c:\users\felip\appdata\local\temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\common\include\jp_primitivetype.h(44): error C3646: 'getItemSize': especificador de substitui‡Æo desconhecido
    c:\users\felip\appdata\local\temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\common\include\jp_primitivetype.h(44): error C2059: erro de sintaxe: ')'
    c:\users\felip\appdata\local\temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\common\include\jp_primitivetype.h(44): error C2238: token(s) inesperado(s) precedendo ';'
    native\common\jp_array.cpp(181): error C2065: 'ssize_t': identificador nÆo declarado
    native\common\jp_array.cpp(181): error C2146: erro de sintaxe: ';' ausente antes do identificador 'itemsize'
    native\common\jp_array.cpp(181): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(182): error C2065: 'ssize_t': identificador nÆo declarado
    native\common\jp_array.cpp(182): error C2146: erro de sintaxe: ';' ausente antes do identificador 'sz'
    native\common\jp_array.cpp(182): error C2065: 'sz': identificador nÆo declarado
    native\common\jp_array.cpp(188): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(188): error C2039: 'getItemSize': nÆo ‚ um membro de 'JPPrimitiveType'
    c:\users\felip\appdata\local\temp\pip-install-byu_puv5\jpype1_3d9482091cbc42b5b84f9271a76b889b\native\common\include\jp_primitivetype.h(20): note: consulte a declara‡Æo de 'JPPrimitiveType'
    native\common\jp_array.cpp(189): error C2065: 'sz': identificador nÆo declarado
    native\common\jp_array.cpp(189): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(193): error C2065: 'sz': identificador nÆo declarado
    native\common\jp_array.cpp(197): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(206): error C2065: 'sz': identificador nÆo declarado
    native\common\jp_array.cpp(216): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(224): error C2065: 'itemsize': identificador nÆo declarado
    native\common\jp_array.cpp(227): error C2065: 'sz': identificador nÆo declarado
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\felip\Projects\CRIA\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\felip\\AppData\\Local\\Temp\\pip-install-byu_puv5\\jpype1_3d9482091cbc42b5b84f9271a76b889b\\setup.py'"'"'; __file__='"'"'C:\\Users\\felip\\AppData\\Local\\Temp\\pip-install-byu_puv5\\jpype1_3d9482091cbc42b5b84f9271a76b889b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\felip\AppData\Local\Temp\pip-record-y84ts2w5\install-record.txt' --single-version-externally-managed --compile 
--install-headers 'C:\Users\felip\Projects\CRIA\venv\include\site\python3.10\JPype1' Check the logs for full command output.
"

Informações Operacionais:

Python 3.10
Executando procedimento em Ambiente Virtual Python a partir de `python -m venv venv`
Processador	AMD FX(tm)-6300 Six-Core Processor                3.50 GHz
RAM instalada	16,0 GB
Tipo de sistema	Windows 10 de 64 bits, processador baseado em x64

Grato desde já.

**Comment by Thrameos** [comment]
JPype 1.3.0 is not compatible with Python 3.10.  Please upgrade the package requirements to JPype 1.4.0.

**Comment by felipefcunica** [comment]
Thanks. Im going to make a pull request!
