### ISSUE TITLE
Problema ao executar o corretor gramatical

### ISSUE THREAD

**Issue by antonionetoo** [gpassero/cogroo4py#3]
Estou tentanto usar o análisador gramátical mas estou tento alguns problemas.

Ao tentar obter os erros a partir do código abaixo, nada é retornado.

```
from cogroo_interface import Cogroo
cogroo = Cogroo.Instance()

doc = cogroo.grammar_check('Elas são bonita.')
doc.mistakes
```

A análise morfossintática está funcionando.

Fiz o build do servidor java novamente mas não resolveu  problema.

Estou usando java/javac 14.0.1  e python 3.6.9
No servidor java não tem nenhum erro, além do Illegal reflective access reportado no projeto.

Estou fazendo algo errado?

**Comment by gpassero** [comment]
Oi @antonionetoo. Lamento que você teve problemas com o corretor. Eu tive problemas também no passado quando tentei rodar ele com versões mais recentes do Java. 

Você poderia verificar se o seu problema também acontece com o Java Runtime 12?

**Comment by gpassero** [comment]
Comparando o comportamento do programa considerando JRE 12 x JRE 14 percebi que apesar de não ser detectado o erro em "Elas são bonita.", funciona a detecção do erro em "Minhas flores é laranjas.". Eu baixei a [versão do repositório para Java 8](https://github.com/gpassero/cogroo4py/releases/tag/v0.2.0) e consegui detectar o erro na frase que você testou, funcionou quando rodei com JRE 8 mas tive erros ao rodar o jar com JRE 10+. Acredito que o problema aconteceu porque Cogroo atualmente não tem suporte para as JREs mais recentes, então a melhor solução que vejo para o momento é usar JRE 8 e a versão do cogroo4py.jar que mencionei acima.

Reverti a versão do repositório para a de Java 8, assim outras pessoas não terão esse problema 🙏
